### ISSUE TITLE
cocoapods is not up to date

### ISSUE THREAD

**Issue by acarioni** [raymccrae/swift-jsonpatch#4]
I’m using your library in an open source project that is distributed by means of SPM. Now I want to release it on Cocoapods as well, but I have a problem: I must specify the version 1.0.4 of your library in the podspec of my project, but the only version of RMJSONPatch available on Cocoapods is the 1.0.0.

Please can you update Cocoapods with the last version available on Github?

**Comment by raymccrae** [comment]
Thanks for getting in contact. I’ll look in to the issue.

**Comment by raymccrae** [comment]
I've pushed the latest podspec to the cocoapods trunk. Please let me know if this has resolved your issue.

**Comment by acarioni** [comment]
It works like a charm. Thank you very much for your support.
