### ISSUE TITLE
cocoapods repo push fails with Xcode 15

### ISSUE THREAD

**Issue by acarioni** [raymccrae/swift-jsonpatch#5]
I am the maintainer of a library that depends on JSONPatch. I appreciate your work on this library and I use it in my project. However, I encountered a problem when I tried to make a new release on Cocoapods. The problem is that since Xcode 14.3, the minimum deployment target for iOS has been increased to 11.0 (the current one for your library is 8.0) and for macOS to 10.12 (the current one is 10.10). The issue is discussed [here](https://github.com/CocoaPods/CocoaPods/issues/11839) and [here](https://github.com/CocoaPods/CocoaPods/issues/12033).

Could you please update the files _RMJSONPatch.podspec_ and _Package.swift_ and make a new release of the library to comply with the latest versions of Xcode?

Also, could you please add the deployment targets for watchOS and tvOS in the podspec and package files? Currently, they are not specified and this may cause compatibility issues for some users.

I tested on the following targets and everything works as expected:

```podspec
s.ios.deployment_target = "11.0"
s.osx.deployment_target = "10.12"
s.watchos.deployment_target = "3.0"
s.tvos.deployment_target = "10.0"

s.swift_versions = ['5']
```

Thank you for your time and attention.

**Comment by raymccrae** [comment]
Hi,

Thanks for writing and bring the matter to my attention. I will look in to updating the package management files.

Regards

**Comment by raymccrae** [comment]
Updated podspec with the changes to deployment targets and swift version release and published to cocoapods.org.
@acarioni if you'd like to verify that things are working for your project.

**Comment by acarioni** [comment]
Everything works now. Thank you very much.
