### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by chrisschlitt** [raymccrae/swift-jsonpatch#6]
Is there any intention to support Linux with this library? In case it's helpful, I'm getting these errors when attempting to build:

```
#18 2.911 [14/884] Compiling JSONPatch JSONElement.swift
#18 2.911 /build/.build/checkouts/swift-jsonpatch/Sources/JSONPatch/JSONElement.swift:161:59: error: 'NSDictionary' is not convertible to '[AnyHashable : Any]'
#18 2.911             let mutable = NSMutableDictionary(dictionary: dictionary)
#18 2.911                                                           ^
#18 2.911 /build/.build/checkouts/swift-jsonpatch/Sources/JSONPatch/JSONElement.swift:161:59: note: did you mean to use 'as!' to force downcast?
#18 2.911             let mutable = NSMutableDictionary(dictionary: dictionary)
#18 2.911                                                           ^
#18 2.911                                                                      as! [AnyHashable : Any]
#18 2.911 /build/.build/checkouts/swift-jsonpatch/Sources/JSONPatch/JSONEquality.swift:29:16: error: cannot find 'CFNumberGetType' in scope
#18 2.911         return CFNumberGetType(self) == .charType
#18 2.911                ^~~~~~~~~~~~~~~
#18 2.911 /build/.build/checkouts/swift-jsonpatch/Sources/JSONPatch/JSONEquality.swift:29:42: error: cannot infer contextual base in reference to member 'charType'
#18 2.911         return CFNumberGetType(self) == .charType
#18 2.911                                         ~^~~~~~~~
#18 2.911 /build/.build/checkouts/swift-jsonpatch/Sources/JSONPatch/JSONPatchCodable.swift:157:16: error: cannot find 'CFNumberGetType' in scope
#18 2.911         switch CFNumberGetType(value) {
#18 2.911                ^~~~~~~~~~~~~~~
#18 2.911 /build/.build/checkouts/swift-jsonpatch/Sources/JSONPatch/NSDictionary+DeepCopy.swift:31:23: error: cannot assign through subscript: subscript is get-only
#18 2.911                 result[key] = array.deepMutableCopy()
#18 2.911                 ~~~~~~^~~~~
#18 2.913 error: fatalError
```

**Comment by raymccrae** [comment]
Hi @chrisschlitt, thanks for reporting these issues regarding linux support. I will look to see the level of effort required for supporting the platform.

**Comment by chrisschlitt** [comment]
Awesome! I'm in desperate need of a package like this for linux, so let me know how I can help in any way!

My hunch is the incomplete porting of `Foundation` outside of Apple Platforms. I saw the issue around `CFNumberGetType` and thought a potential fix would be conditionally importing the newer `FoundationNetworking` framework but sadly that didn't seem to fix it.

**Comment by raymccrae** [comment]
I've created a branch called `feature/linux-support`. I need to install a linux distro on a vm, as I don't have an environment to test changes.

With regards to `CFNumberGetType`, I had a look at [NSNumber.swift](https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/NSNumber.swift) in the swift corelibs, I'm thinking that property `objCType` could be used. Something like the following.

```
#if os(Linux)
return objCType.pointee == 0x63 // character code for 'c'
#else
return CFNumberGetType(self) == .charType
#endif
```

**Comment by chrisschlitt** [comment]
I can test things if you need. That does sound like a good solution, when replacing the instance in `JSONPatchCodable.swift`, I tried changing the switch to: 
```
#if os(Linux)
switch value.objCType.pointee {
case 0x63:
    try encode(value.boolValue)
case 0x64, 0x71, 0x51, 0x4C:
    try encode(value.doubleValue)
case 0x66, 0x49:
    try encode(value.floatValue)
default:
    try encode(value.int64Value)
}
#else
switch CFNumberGetType(value) {
case .charType:
    try encode(value.boolValue)
case .cgFloatType, .doubleType, .float64Type:
    try encode(value.doubleValue)
case .floatType, .float32Type:
    try encode(value.floatValue)
default:
    try encode(value.int64Value)
}
#endif
```
and it will successfully compile, but when trying to generate a patch I get a crash with:
```
Could not cast value of type 'Swift.String' (0xaaaaca3c58a0) to 'JSONPatch.JSONEquatable' (0xaaaacc327580).
```

**Comment by raymccrae** [comment]
Regarding the fatalError from the cast, I think we'd need a similar extension on `String` as we do for `NSString` in `JSONEquality.swift`.

```
extension NSString: JSONEquatable {
    func isJSONEquals(to element: JSONElement) -> Bool {
        guard case let .string(str) = element else {
            return false
        }

        return isEqual(str)
    }
}
```

**Comment by chrisschlitt** [comment]
I added similar extensions for String, Array, and Dictionary and it now builds and runs successfully! At least in my initial testing of generating a patch between two codable objects. This is awesome!

Do you want me to open a PR for this? Or do you want to handle it?

**Comment by chrisschlitt** [comment]
A bit messy, but this is what I tried: https://github.com/chrisschlitt/swift-jsonpatch/blob/feature/linux-support/Sources/JSONPatch/JSONEquality.swift

**Comment by raymccrae** [comment]
> Do you want me to open a PR for this? Or do you want to handle it?

I think it would be good if you opened a pull request, that way you can get the contributor recognition. I can clean up the code, if required after.

**Comment by chrisschlitt** [comment]
Thanks!

Opened a pull request here: https://github.com/raymccrae/swift-jsonpatch/pull/7

Let me know if I should have opened it against the branch instead

**Comment by raymccrae** [comment]
Thanks @chrisschlitt, I updated the pr to target the develop branch, and I've accepted and merged the pr. I'd like to get the unit tests running on linux before making the release, just to check there are no issues.

**Comment by cschlittPHI** [comment]
A good confirmation imo! Thanks for getting to this so quickly and letting me help. No rush on the merge (I’m developing off this branch for now)

**Comment by raymccrae** [comment]
Release v1.0.6 published
